"""updated rel

Revision ID: 08bc6888b94b
Revises: e8b3e7e7430e
Create Date: 2022-11-01 14:52:38.973374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08bc6888b94b'
down_revision = 'e8b3e7e7430e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('desc', sa.Integer(), nullable=True))
    op.drop_index('ix_actions_action_description', table_name='actions')
    op.create_index(op.f('ix_actions_desc'), 'actions', ['desc'], unique=False)
    op.create_foreign_key(None, 'actions', 'changes', ['desc'], ['id'], ondelete='CASCADE')
    op.drop_column('actions', 'action_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('action_description', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.drop_index(op.f('ix_actions_desc'), table_name='actions')
    op.create_index('ix_actions_action_description', 'actions', ['action_description'], unique=False)
    op.drop_column('actions', 'desc')
    # ### end Alembic commands ###
