"""'role'

Revision ID: 12ac265556c2
Revises: 6f62f1fe4d94
Create Date: 2022-10-25 00:29:12.739662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ac265556c2'
down_revision = '6f62f1fe4d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_roles_role'), 'roles', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_role'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
