"""added delete field in tasks clumn

Revision ID: 2619495dceea
Revises: 1bc285f50bea
Create Date: 2022-11-04 11:20:58.736884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2619495dceea'
down_revision = '1bc285f50bea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'actions', 'changes', ['action_description'], ['id'], ondelete='CASCADE')
    op.drop_column('actions', 'description')
    op.drop_column('actions', 'desc')
    op.add_column('tasks', sa.Column('deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deleted')
    op.add_column('actions', sa.Column('desc', sa.INTEGER(), nullable=True))
    op.add_column('actions', sa.Column('description', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'actions', type_='foreignkey')
    # ### end Alembic commands ###
