"""add phone user

Revision ID: 281b7ba94eb5
Revises: 5beb8351562d
Create Date: 2022-10-12 02:01:27.289702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281b7ba94eb5'
down_revision = '5beb8351562d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
