"""deleted added

Revision ID: 3d7101d2321e
Revises: 32a328a48811
Create Date: 2022-11-04 15:01:48.916277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7101d2321e'
down_revision = '32a328a48811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'changes', ['action_description'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('description')
        batch_op.drop_column('desc')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
