"""add comment model

Revision ID: 607f5b676838
Revises: 9d997c09e56d
Create Date: 2022-11-01 18:31:19.957255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607f5b676838'
down_revision = '9d997c09e56d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_task_id'), 'comment', ['task_id'], unique=False)
    op.create_index(op.f('ix_comment_user_id'), 'comment', ['user_id'], unique=False)
    op.drop_index('ix_roles_role', table_name='roles')
    op.create_unique_constraint(None, 'roles', ['role'])
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'roles', type_='unique')
    op.create_index('ix_roles_role', 'roles', ['role'], unique=False)
    op.drop_index(op.f('ix_comment_user_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_task_id'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
