"""Added creator and responsible

Revision ID: 6e9e512cdceb
Revises: 281b7ba94eb5
Create Date: 2022-10-14 21:49:50.697477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9e512cdceb'
down_revision = '281b7ba94eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('creator', sa.String(), nullable=False))
    op.add_column('tasks', sa.Column('responsible', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'responsible')
    op.drop_column('tasks', 'creator')
    # ### end Alembic commands ###
