"""added actions model

Revision ID: 7ecc917faee2
Revises: 9d997c09e56d
Create Date: 2022-10-31 22:30:07.166618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ecc917faee2'
down_revision = '9d997c09e56d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_changes_description'), 'changes', ['description'], unique=False)
    op.create_index(op.f('ix_changes_name'), 'changes', ['name'], unique=True)
    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_user', sa.Integer(), nullable=True),
    sa.Column('action_object', sa.Integer(), nullable=True),
    sa.Column('action_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['action_object'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['action_user'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_actions_action_object'), 'actions', ['action_object'], unique=False)
    op.create_index(op.f('ix_actions_action_user'), 'actions', ['action_user'], unique=False)
    op.drop_index('ix_action_action_datetime', table_name='action')
    op.drop_index('ix_action_action_description', table_name='action')
    op.drop_index('ix_action_action_user', table_name='action')
    op.drop_index('ix_action_object_name', table_name='action')
    op.drop_table('action')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.INTEGER(), nullable=True))
    op.create_table('action',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('object_name', sa.VARCHAR(), nullable=False),
    sa.Column('action_user', sa.VARCHAR(), nullable=False),
    sa.Column('action_description', sa.VARCHAR(), nullable=False),
    sa.Column('action_datetime', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_action_object_name', 'action', ['object_name'], unique=False)
    op.create_index('ix_action_action_user', 'action', ['action_user'], unique=False)
    op.create_index('ix_action_action_description', 'action', ['action_description'], unique=False)
    op.create_index('ix_action_action_datetime', 'action', ['action_datetime'], unique=False)
    op.drop_index(op.f('ix_actions_action_user'), table_name='actions')
    op.drop_index(op.f('ix_actions_action_object'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_changes_name'), table_name='changes')
    op.drop_index(op.f('ix_changes_description'), table_name='changes')
    op.drop_table('changes')
    # ### end Alembic commands ###
