"""added action model

Revision ID: 9d997c09e56d
Revises: 432cb7303002
Create Date: 2022-10-29 13:19:17.452556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d997c09e56d'
down_revision = '432cb7303002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_action_object_id', table_name='action')
    op.create_index(op.f('ix_action_action_datetime'), 'action', ['action_datetime'], unique=False)
    op.drop_column('action', 'object_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('object_id', sa.INTEGER(), nullable=False))
    op.drop_index(op.f('ix_action_action_datetime'), table_name='action')
    op.create_index('ix_action_object_id', 'action', ['object_id'], unique=False)
    # ### end Alembic commands ###
