"""'status'

Revision ID: ad1182263b07
Revises: 12ac265556c2
Create Date: 2022-10-25 00:38:41.532422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1182263b07'
down_revision = '12ac265556c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_statuses_description', table_name='statuses')
    op.drop_index('ix_statuses_name', table_name='statuses')
    op.drop_table('statuses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statuses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_statuses_name', 'statuses', ['name'], unique=False)
    op.create_index('ix_statuses_description', 'statuses', ['description'], unique=False)
    # ### end Alembic commands ###
