"""updated relations

Revision ID: c226a52447c7
Revises: 9b3b327bfd1c
Create Date: 2022-11-02 00:05:07.956331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c226a52447c7'
down_revision = '9b3b327bfd1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_actions_description', table_name='actions')
    op.create_index(op.f('ix_actions_action_description'), 'actions', ['action_description'], unique=False)
    op.create_foreign_key(None, 'actions', 'changes', ['action_description'], ['id'], ondelete='CASCADE')
    op.drop_column('actions', 'desc')
    op.drop_column('actions', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('description', sa.INTEGER(), nullable=True))
    op.add_column('actions', sa.Column('desc', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.drop_index(op.f('ix_actions_action_description'), table_name='actions')
    op.create_index('ix_actions_description', 'actions', ['description'], unique=False)
    # ### end Alembic commands ###
