"""added actions changes model

Revision ID: e8b3e7e7430e
Revises: 7ecc917faee2
Create Date: 2022-10-31 22:52:14.837238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b3e7e7430e'
down_revision = '7ecc917faee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('action_description', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_actions_action_description'), 'actions', ['action_description'], unique=False)
    op.create_foreign_key(None, 'actions', 'changes', ['action_description'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.drop_index(op.f('ix_actions_action_description'), table_name='actions')
    op.drop_column('actions', 'action_description')
    # ### end Alembic commands ###
